language: python
python:
- '3.6'
install:
- pip install ansible>=2.4 molecule apache-libcloud pycrypto
script:
- molecule --debug create
- molecule --debug converge
- molecule verify
after_script:
- molecule destroy
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: JT6o7U1oHKYbhg1TXUz2WTpwspgs0oHdeTChJCrXre+GArpsLeakF2LNbdLEjYDPpJVORHGto5WTfDRxirp/+O2hINL7EWooYJ2JUhP4343lwymrr8v6FYQp5wbljKr9WzNuq0RRKBP0+jzmgMnAB7tn/RioTlFJJ7FL1Kud4UQenW/mhxnGiBTuBqwLFeMoFJYV0BJbEMtIgufIIfUiJv+BJOejiCARjIk2PPn4RuiIpDl9nwuUE7OimzQTuR1w97HfUq5wb8h+jeiBn6+MnQMMqOgNG9NSw4+w5V5/djxER8r4FYxNO0/icxbdbzfSnuwenxmesdeaTM9Ap42Vlb50hHJYDMJpbm7XStbvtcvi5yByb9gsa14FPikbkQI2muF/GX7JYVOF/o2zRt3o53UKw6M8I/FLwxb3dBzF3SzcI9faYgaw0DqzYkIzjF087jnaFBbKisWe7n8ob8r4VP8lI1gCNiovHBANYzstcLSWIeL5+V9bCDoxEI0fDfzbUyJSOwDWiwVMakzBeAS5x9LDnfnyLbFOfBOs3PPVuA5H1yDWjG96WIv+huO4jzaeXNhk1wygQFxFxzFN3fA8znL+OPsrEaDOpNetGU8Mcq9KWTQ4dyjw+DVId0t4IKSoeqVI6YefIAlrkwACHYbU8dkcyV/J5OMdj2Z2XM+Ph6Y=
  - secure: TaQfPZCTpTZP9WyFfJC4tnXu44kROrvHGGrgsEOzD2wmKXxPP5uy0PkBmgcoomJwhqXJoCRbNMM+uj+pXTV/4jU4ysck3psYvHlpVxdzMkkEVmAhL58XxEg5YhFesLZwAzG5YUFgINdZ4S58E6jy0BpZXDuavPY6Vqea/Ngkw1WJydN8uXzCyBsjzYOe/t11I1p5pjsQ6uQ11Kyu2ATBdsdgPD50N2Glt1Pt9Mew8qkStGJ6CseFqBEyh/GzuO8Id6FsDojbLNgAQ4D1rJrotjk+QtWFgUprUAqHRB3uTV7XpHGoBXU+2BTLllVXUm5ru2VaCrwQCjdzmm7A3w9NLkSUm8cXCxxtaAJsMAPxsqmjteqTguaAfAm92AktR7GLeJCXHTqPNkoiIdfbqsLdwoHkamm1UkXjYBP2a34IvJWDbXyLs7DOSVCVoGA4ueNryqSYzsAG9Oq4GEEHdeGZ8vwX5cAgnWjcf1fDCSVPGvLpcpBqMIgrj+qRPIjhczwtsH953T8s5aCOtXaS4DsfjlTr6PoVyrAxlsmyk2Hom0julZGakEHN6VRZxYmyVYC4LeGwxKVmqRYo2p9IPBOZtdNjl08c+cl4bY81TN0a869dNaaQlfeXmk0NHuA+5464RD/8DG7Ld9aQqSVdNC1i0eBagjEjbW9PFw8dG+Iy1nA=
  - secure: hrwZZlQ6snrs7Fc3f8lCqMzwpOqErulEb5zw5ULaW2bLyerrMub8kW0OtVE4fVUIM1Qmjh44bgPJUuPf/XFR/0pz+FlOIL2h6XObRUOCGCcPcm62jTH1jry/YtN+8RXRSaJM+kdxCVZMpJA91n6ncwlPtuyCRgUyKl0gfgUaqEQDqPFprJyoQ2uldhNKBRflMszY8DFu177RgTbDdfxsGU+X53lCgaprBP4KtoGrUcy0P6JLlJ6640eTZESXOpJNvu0AvIbFt1cyC57MS3o620fjWd5bW8Lc8SAumoYPo/Qh7Ds1jMwZY/dglUjYxjoXLy/5dlRDMsnvBt1AcciRtEJgZDLbk/53+VqXTFOHKPXfBtsYYkmuJPDw4JJhQ5PqGwqEvqaOFUyqhUpGFqawCu29USxHHgD80wkYL/ZkvrTkSCiDP+4zmmJFeJMv4XL0X0V8NxPRnKNyen8kRyCvlMIvGmBDsn/yIE1bAfmIFnMxHhg3VHVe+mwiEvUln5cG+4vBNyq3GV//S56jLFBstSBI79nbXNh54IlcZFrXbBPuVIqA+29Y4udJf6+krfnIZZl6Tf0lVpwJMxHQ9RtO6gH44pu6siE4MVpwCXpO+aNMtmMNT8PTzQWYTDltJi3Q1YceH/GLJXFLvMeh7g6ixJduAMKcDX3Tr6ji/DuTEtI=
before_install:
- openssl aes-256-cbc -K $encrypted_1948b550b48a_key -iv $encrypted_1948b550b48a_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    rooms:
      secure: bT4kjqyYtBv9phRnah2TtA0lwnjUgY/ul2wZdDuvKxNLuPJPy5htA8IsbucX/vKYCG/dAif0nsqJTfCnhMtOQHKtZm6l4gfJJcOihdW2CmG+1WREwXTX/MVH9UsheWB9++drjMGLbTHHIyshX8mMeya4xjH2J/VsS9c+wArUCv489KmWFvW+newYuZYyXH8yipuZrwA5tOIKMWP0fnhaTis90fan5x/YAmM75TMvrJYekakm5+pEZ2ol+4hL39k5dnfZLfttZfaUtgOFzaULTdTqgwqhzkGk507nBMQ6pYWXgjcCBCPKZf8whTW7YlvW1yBCjCDjBG1XdoYcZInHh+u8u35aqN0Ck2nFlpEKbNCjmwzEqkHSS5vuZ3J1WY94Nbk0I7IvLb3HMXBjym3qPProgyU7qxtAARzTl2yCPYn2FNpO20X7KhhnzV4ekCrPLizbVl0sDwPNOP1voIvJzDhmQmx4xymMRg07lUnFXtvUT+nSy3F5pJXvHFL2ycn3TjD0P+yj+LhuEgAYzUPqdeh+D8gt1oetCGNf0BnL8SnWoi8XJVJoiQv0xStC02ROK1NdwSjnHV/fmUddACPymZneMUkyZgSlh4ywLMKs2mG8KrWNMwazADQ5XBchqXkGpbMKBHQ49ZqzXXMRy9lnMCUCjlDBvzG+6WsoOhPWsHA=

