# tasks file for db
  - name: Add APT key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com
    tags: install

  - name: Add mongoDB repo
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
    tags: install

  - name: Install mongoDB
    apt:
      name: mongodb-org
      state: present
      update_cache: yes
    tags: install

  - name: Enable mongoDB service
    systemd: name=mongod enabled=yes
    tags: install

