---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: instance-travis
    zone: us-west1-a
    machine_type: f1-micro
    image: ubuntu/xenial64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
